#!/bin/bash
#
# spamholed	This shell script takes care of starting and stopping
#		spamhole
#
# chkconfig: 345 80 80 
# description: spamhole is a spam honeypot.

# Source function library.
. /etc/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# for use later when spamhole grows.. =)
#if [ -f /etc/sysconfig/spamhole ];then
#        . /etc/sysconfig/spamhole
#fi

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

# need to get mail relay addr from conf file
# should have a line MAILRELAY=x.x.x.x
spamconf=/etc/spamhole.conf

#[ -x /usr/sbin/spamhole -a -f $spamconf ] || exit 0
[ -x /usr/sbin/spamhole ] || exit 0

RETVAL=0
prog="spamhole"

start() {
        # Start daemons.
        echo -n $"Starting $prog: "
        daemon spamhole $OPTIONS
	RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/spahmole
	return $RETVAL
}

stop() {
        # Stop daemons.

        echo -n $"Shutting down $prog: "
	killproc spamhole
	RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/spamhole
	return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
        ;;
  stop)
	stop
        ;;
  status)
	status spamhole
	RETVAL=$?
	;;
  restart|reload)
	stop
	start
	RETVAL=$?
	;;
  condrestart)
	if [ -f /var/lock/subsys/spamhole ]; then
	    stop
	    start
	    RETVAL=$?
	fi
	;;
  *)
        echo $"Usage: $0 {start|stop|restart|condrestart|status}"
        exit 1
esac

exit $RETVAL
